# Generated by Django 4.1.2 on 2022-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='images')),
                ('address', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('explain', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='head',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tail',
        ),
    ]
