# Generated by Django 4.1.2 on 2022-10-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_about_services_remove_project_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
