# Generated by Django 4.1.2 on 2022-10-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(verbose_name='النص'),
        ),
    ]
