# Generated by Django 4.1.2 on 2022-10-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='about',
            name='logo',
            field=models.ImageField(upload_to='images', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='about',
            name='url',
            field=models.CharField(max_length=100, verbose_name='رابط الموقع'),
        ),
    ]
