# Generated by Django 4.1.2 on 2022-10-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_about_address_alter_about_logo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='offer',
            name='text',
            field=models.TextField(max_length=400, verbose_name='نص العرض'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان العرض'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='اسم الصورة'),
        ),
    ]
